vim.cmd('colorscheme base16-gruvbox-dark-soft')

vim.cmd("hi Normal guibg=none ctermbg=none")
vim.cmd("hi LineNr guibg=none ctermbg=none")
vim.cmd("hi Folded guibg=none ctermbg=none")
vim.cmd("hi SpecialKey guibg=none ctermbg=none")
vim.cmd("hi VertSplit guibg=none ctermbg=none")
vim.cmd("hi SignColumn guibg=none ctermbg=none")
vim.cmd("hi PMenu guibg=none ctermbg=none")
vim.cmd("hi NvimTreeNormal guibg=none ctermbg=none")
vim.cmd("hi NormalFloat guibg=none ctermbg=none")
